export const INGESTION_CONSTANTS = {
  TITLE: 'Surplus Ingestion Pipeline',
  SUBTITLE: 'Progressive disclosure telemetry, automated shelf-life validation, and inventory liquidation allocations.',
  FALLBACK_TELEMETRY: {
    PORTFOLIO_VALUE: '$1,842,900',
    PORTFOLIO_SUBTEXT: 'FEFO Managed',
    CRITICAL_RSL: '18 Lots',
    CRITICAL_RSL_SUBTEXT: 'Immediate Auction',
    LIQUIDATION_VELOCITY: '94.8%',
    LIQUIDATION_VELOCITY_SUBTEXT: '+3.2% vs Target',
    BUYER_NETWORK: '50 Verified',
    BUYER_NETWORK_SUBTEXT: '100% Compliant',
  },
  DEFAULT_COUNTS: {
    INVENTORY: 100,
    SALES: 92,
    BUYERS: 50,
  },
  CONNECTORS: {
    ZAPIER_FEEDBACK: 'Zapier webhook endpoint copied to clipboard!',
    SHEETS_FEEDBACK: 'Google Sheets OAuth authorization initialized.',
    SCANNER_FEEDBACK: 'Opening document OCR scanner modal...',
    DIRECTORY_FEEDBACK: 'Integrations Directory: NetSuite, SAP ERP, Shopify Plus, Amazon FBA, EDI 856 & Webhooks are available for enterprise setup.',
  },
  MODAL: {
    TITLE: 'Unified Surplus Data Ingestion',
    SUBTITLE: 'Upload multi-source surplus catalogs, sales reconciliation reports, or buyer networks with automated schema detection.',
    DESTINATIONS: [
      {
        id: 'inventory',
        title: 'Inventory Data',
        description: 'Surplus food & CPG inventory lots, expiry dates, warehouses, and valuations.',
        icon: 'inventory_2',
        badge: 'FEFO Tracking',
      },
      {
        id: 'sales',
        title: 'Sales Data',
        description: 'Distributor closeout invoices, sold quantities, unit pricing, and allocations.',
        icon: 'point_of_sale',
        badge: 'Reconciliation',
      },
      {
        id: 'buyers',
        title: 'Buyer Data',
        description: 'B2B commercial liquidators, discount retail buyers, and non-profit accounts.',
        icon: 'domain',
        badge: 'Direct Network',
      },
    ],
  },
  INVENTORY_FILTER_DEFAULTS: {
    SUPPLIERS: [
      'Unilever Direct',
      'Kraft Heinz Co',
      'PepsiCo Supply',
      'Tyson Foods',
      'Del Monte',
    ],
    DCS: [
      'Northeast Hub',
      'Texas Central',
      'Pacific Northwest',
      'Midwest Logistics Hub',
    ],
    CATEGORIES: [
      'Chilled & Dairy',
      'Ambient / Beverages',
      'Condiments',
      'Deep Freeze',
      'Surplus Overstock',
    ],
    STATUSES: [
      'Critical RSL',
      'Stable RSL',
      'Urgent RSL',
      'Active List',
      'Sold',
    ],
  },
  INVENTORY_MAPPING_OPTIONS: [
    { value: 'sku', label: 'SKU' },
    { value: 'description', label: 'Description' },
    { value: 'brand', label: 'Brand' },
    { value: 'category', label: 'Category' },
    { value: 'subCategory', label: 'Sub-Category' },
    { value: 'quantity', label: 'Quantity (Cases)' },
    { value: 'availableQty', label: 'Available Qty' },
    { value: 'expirationDate', label: 'Expiration Date' },
    { value: 'originalPrice', label: 'Original Price' },
    { value: 'lotNumber', label: 'Lot Number' },
    { value: 'productionDate', label: 'Production Date' },
    { value: 'standardSellPrice', label: 'List Price' },
    { value: 'status', label: 'Status (Active/Sold)' },
    { value: 'temperatureMin', label: 'Min Temp (°F)' },
    { value: 'temperatureMax', label: 'Max Temp (°F)' },
    { value: 'warehouse', label: 'Warehouse / DC' },
  ],
  SALES_FILTER_DEFAULTS: {
    BUYERS: [
      'Whole Foods Market Regional',
      'Metro Salvage Provisions',
      'Appalachian Fresh Outlets',
      'Big Lots Food Disposals',
    ],
    DCS: [
      'Northeast Logistics Hub, Newark',
      'Texas Central Facility, Dallas',
      'Pacific Northwest Hub',
    ],
    PRICE_RANGES: [
      '< $10/cs',
      '$10 - $20/cs',
      '> $20/cs',
    ],
    STATUSES: [
      'Completed / Settled',
      'Pending Escrow',
      'Invoiced',
    ],
  },
  SALES_MAPPING_OPTIONS: [
    { value: 'sku', label: 'SKU' },
    { value: 'description', label: 'Description' },
    { value: 'brand', label: 'Brand' },
    { value: 'lotNumber', label: 'Lot Number' },
    { value: 'buyerEmail', label: 'Buyer Email' },
    { value: 'buyerCompany', label: 'Buyer Company' },
    { value: 'quantity', label: 'Quantity Sold (Cases)' },
    { value: 'price', label: 'Price Per Case' },
    { value: 'totalValue', label: 'Total Value' },
    { value: 'revenue', label: 'Total Revenue' },
    { value: 'saleDate', label: 'Sale Date' },
    { value: 'invoiceNumber', label: 'Invoice #' },
    { value: 'productName', label: 'Product Name' },
    { value: 'status', label: 'Status' },
    { value: 'warehouse', label: 'Warehouse / DC' },
  ],
  DEFAULT_SALES_RECORDS: [
    {
      _id: 'sales-row-1',
      contractNumber: 'ORD-2026-9941',
      invoiceNumber: 'INV-2026-9941',
      productName: 'Oscar Mayer Deli Slices',
      description: 'Oscar Mayer Deli Slices',
      sku: 'OM-DEL-3310',
      lotNumber: '#001',
      buyerName: 'Whole Foods Market Regional',
      buyerCompany: 'Whole Foods Market Regional',
      buyerNode: 'Mid-Atlantic Hub',
      warehouse: 'Northeast Logistics Hub, Newark',
      dc: 'Northeast Logistics Hub, Newark',
      storageTemp: 'Reefer 36°F',
      dockType: 'Reefer 36°F',
      quantitySold: 5400,
      pricePerCase: 14.2,
      totalRevenue: 76680,
      totalValue: 76680,
      status: 'Completed / Settled',
      saleDate: '09/18/2026',
      dateRecorded: 'Sep 18, 2026',
      createdAt: '2026-09-18T09:30:00.000Z',
      updatedAt: '2026-09-19T14:15:00.000Z',
      trackingCarrier: 'SWF-90214-VA • Swift Cold Logistics',
      deliveryWindow: 'Mar 21, 08:00 EST',
      grossSale: 76680.0,
      netRemitted: 73612.8,
    },
    {
      _id: 'sales-row-2',
      contractNumber: 'ORD-2026-9942',
      invoiceNumber: 'INV-2026-9942',
      productName: 'Kraft Dressings Bulk Pack',
      description: 'Kraft Dressings Bulk Pack',
      sku: 'KF-DRS-1102',
      lotNumber: '#004',
      buyerName: 'Metro Salvage Provisions',
      buyerCompany: 'Metro Salvage Provisions',
      buyerNode: 'Southeast Node',
      warehouse: 'Texas Central Facility, Dallas',
      dc: 'Texas Central Facility, Dallas',
      storageTemp: 'Ambient Dock',
      dockType: 'Ambient Dock',
      quantitySold: 9800,
      pricePerCase: 5.4,
      totalRevenue: 52920,
      totalValue: 52920,
      status: 'Pending Escrow',
      saleDate: '09/18/2026',
      dateRecorded: 'Sep 18, 2026',
      createdAt: '2026-09-18T10:15:00.000Z',
      updatedAt: '2026-09-18T16:40:00.000Z',
      pickupTerms: 'Customer Pickup (CPU)',
      appointmentTerms: 'Dock Door #4 (14:30 EST)',
      grossSale: 52920.0,
      escrowStatus: '100% Funded',
    },
    {
      _id: 'sales-row-3',
      contractNumber: 'ORD-2026-9945',
      invoiceNumber: 'INV-2026-9945',
      productName: 'Pure Leaf Real Tea 18.5oz',
      description: 'Pure Leaf Real Tea 18.5oz',
      sku: 'PL-TEA-5542',
      lotNumber: '#003',
      buyerName: 'Appalachian Fresh Outlets',
      buyerCompany: 'Appalachian Fresh Outlets',
      buyerNode: 'Discount Network',
      warehouse: 'Pacific Northwest Hub',
      dc: 'Pacific Northwest Hub',
      storageTemp: 'Ambient Freight',
      dockType: 'Ambient Freight',
      quantitySold: 11200,
      pricePerCase: 8.9,
      totalRevenue: 99680,
      totalValue: 99680,
      status: 'Pending Escrow',
      saleDate: '09/18/2026',
      dateRecorded: 'Sep 18, 2026',
      createdAt: '2026-09-18T11:20:00.000Z',
      updatedAt: '2026-09-18T18:00:00.000Z',
      telemetryGps: 'I-80 Eastbound (Mile Marker 192)',
      telemetrySpeed: '62 mph • On schedule',
      settlementTerms: '$99,680.00 (Net 15 Days)',
      grossSale: 99680.0,
    },
  ],
  BUYER_FILTER_DEFAULTS: {
    TIERS: [
      'Tier 1',
      'Tier 2',
      'Custom',
      'Liquidator',
    ],
    STATUSES: [
      'Active Compliant',
      'Full Opt-In',
      'Allergen Filter',
      'Active Buyers',
      'Inactive Buyers',
      'Opt-Out Bidding',
      'Opt-Out Sales',
    ],
  },
  DEFAULT_BUYER_RECORDS: [
    {
      _id: 'buyer-row-1',
      buyerId: 'BYR-ALB-001',
      companyName: 'Albertsons Pacific Northwest',
      name: 'Albertsons Pacific Northwest',
      email: 's.lin@albertsons-pnw.com',
      tier: 'Tier 1',
      networkSubtitle: 'ID: BYR-ALB-001 • 148 Stores',
      preferencesPrimary: 'Chilled & Frozen Priority',
      preferencesSecondary: 'Full Opt-In • SQF Level 3',
      createDate: '01/14/2025',
      updateDate: '09/17/2026',
      status: 'Active Compliant',
      isActive: true,
      optInBidding: true,
      optInSales: true,
      procurementOfficers: [
        { name: 'Sarah Lin', title: 'Director of Remediation', email: 's.lin@albertsons-pnw.com' }
      ],
      categories: ['Dairy & Chilled', 'Frozen Meat'],
      hubFacilities: ['DC #19 (Auburn, WA)'],
      tenderActionType: 'Send Lot Tender',
    },
    {
      _id: 'buyer-row-2',
      buyerId: 'BYR-APP-009',
      companyName: 'Appalachian Fresh Outlets',
      name: 'Appalachian Fresh Outlets',
      email: 'm.callahan@app-fresh.com',
      tier: 'Tier 2',
      networkSubtitle: 'ID: BYR-APP-009 • 34 Discount Stores',
      preferencesPrimary: 'Deep Discount & Salvage',
      preferencesSecondary: 'Dry & Ambient (Short RSL <7d)',
      createDate: '03/22/2025',
      updateDate: '09/15/2026',
      status: 'Active Compliant',
      isActive: true,
      optInBidding: true,
      optInSales: true,
      procurementOfficers: [
        { name: 'Mark Callahan', title: 'Buyer', email: 'm.callahan@app-fresh.com' }
      ],
      categories: ['Specialty Remnants', 'Dry & Ambient (Short RSL <7d)'],
      hubFacilities: ['Roanoke Regional Depot, VA'],
      tenderActionType: 'Forward Short-Dated Offers',
    },
    {
      _id: 'buyer-row-3',
      buyerId: 'BYR-FB-ATL',
      companyName: 'Atlanta Community Food Bank',
      name: 'Atlanta Community Food Bank',
      email: 'e.rostova@acfb.org',
      tier: 'Custom',
      networkSubtitle: 'ID: BYR-FB-ATL • 700+ Agencies',
      preferencesPrimary: 'Zero-Waste Donation Channel',
      preferencesSecondary: 'IRC 170(e)(3) • Allergen Filter',
      createDate: '05/10/2025',
      updateDate: '09/18/2026',
      status: 'Active Compliant',
      isActive: true,
      optInBidding: false,
      optInSales: false,
      procurementOfficers: [
        { name: 'Elena Rostova', title: 'Donation Officer', email: 'e.rostova@acfb.org' }
      ],
      categories: ['Zero-Waste Donation Channel', 'Form 8283 Auto Generation'],
      hubFacilities: ['Free 24h carrier dispatch'],
      tenderActionType: 'Route Zero-Waste Donation',
    },
    {
      _id: 'buyer-row-4',
      buyerId: 'BYR-BL-501',
      companyName: 'Big Lots Food Disposals & Overstock',
      name: 'Big Lots Food Disposals & Overstock',
      email: 'd.vance@biglots-closeout.com',
      tier: 'Liquidator',
      networkSubtitle: 'ID: BYR-BL-501 • 1,300+ Outlets',
      preferencesPrimary: 'Bulk Closeout Container Purchases',
      preferencesSecondary: 'Ambient Dry Specialists • Min 5 FTL',
      createDate: '02/08/2025',
      updateDate: '09/16/2026',
      status: 'Active Compliant',
      isActive: true,
      optInBidding: true,
      optInSales: true,
      procurementOfficers: [
        { name: 'David Vance', title: 'Lead Buyer', email: 'd.vance@biglots-closeout.com' }
      ],
      categories: ['Bulk Closeout Containers', 'Min. 5 FTL per transaction'],
      hubFacilities: ['Central Logistics (Columbus, OH)'],
      tenderActionType: 'Push Multi-Truckload Batch',
    },
  ],
} as const;


