export const INGESTION_CONSTANTS = {
  TITLE: 'Surplus Ingestion Pipeline',
  SUBTITLE: 'Progressive disclosure telemetry, automated shelf-life validation, and inventory liquidation allocations.',
  FALLBACK_TELEMETRY: {
    PORTFOLIO_VALUE: '$0',
    PORTFOLIO_SUBTEXT: 'FEFO Managed',
    CRITICAL_RSL: '0 Lots',
    CRITICAL_RSL_SUBTEXT: 'Immediate Auction',
    LIQUIDATION_VELOCITY: '0%',
    LIQUIDATION_VELOCITY_SUBTEXT: '+0% vs Target',
    BUYER_NETWORK: '0 Verified',
    BUYER_NETWORK_SUBTEXT: '100% Compliant',
  },
  DEFAULT_COUNTS: {
    INVENTORY: 0,
    SALES: 0,
    BUYERS: 0,
  },
  CONNECTORS: {
    ZAPIER_FEEDBACK: 'Zapier webhook endpoint copied to clipboard!',
    SHEETS_FEEDBACK: 'Google Sheets OAuth authorization initialized.',
    SCANNER_FEEDBACK: 'Opening document OCR scanner modal...',
    DIRECTORY_FEEDBACK: 'Integrations Directory: NetSuite, SAP ERP, Shopify Plus, Amazon FBA, EDI 856 & Webhooks are available for enterprise setup.',
  },
  MODAL: {
    TITLE: 'Unified Surplus Data Ingestion',
    SUBTITLE: 'Upload multi-source surplus catalogs, sales reconciliation reports, or buyer networks with automated schema detection.',
    DESTINATIONS: [
      {
        id: 'inventory',
        title: 'Inventory Data',
        description: 'Surplus food & CPG inventory lots, expiry dates, warehouses, and valuations.',
        icon: 'inventory_2',
        badge: 'FEFO Tracking',
      },
      {
        id: 'sales',
        title: 'Sales Data',
        description: 'Distributor closeout invoices, sold quantities, unit pricing, and allocations.',
        icon: 'point_of_sale',
        badge: 'Reconciliation',
      },
      {
        id: 'buyers',
        title: 'Buyer Data',
        description: 'B2B commercial liquidators, discount retail buyers, and non-profit accounts.',
        icon: 'domain',
        badge: 'Direct Network',
      },
    ],
  },
  INVENTORY_FILTER_DEFAULTS: {
    SUPPLIERS: [
      'Unilever Direct',
      'Kraft Heinz Co',
      'PepsiCo Supply',
      'Tyson Foods',
      'Del Monte',
    ],
    DCS: [
      'Northeast Hub',
      'Texas Central',
      'Pacific Northwest',
      'Midwest Logistics Hub',
    ],
    CATEGORIES: [
      'Chilled & Dairy',
      'Ambient / Beverages',
      'Condiments',
      'Deep Freeze',
      'Surplus Overstock',
    ],
    STATUSES: [
      'Critical RSL',
      'Stable RSL',
      'Urgent RSL',
      'Active List',
      'Sold',
    ],
  },
  INVENTORY_MAPPING_OPTIONS: [
    { value: 'sku', label: 'SKU' },
    { value: 'description', label: 'Description' },
    { value: 'brand', label: 'Brand' },
    { value: 'category', label: 'Category' },
    { value: 'subCategory', label: 'Sub-Category' },
    { value: 'quantity', label: 'Quantity (Cases)' },
    { value: 'availableQty', label: 'Available Qty' },
    { value: 'expirationDate', label: 'Expiration Date' },
    { value: 'originalPrice', label: 'Original Price' },
    { value: 'lotNumber', label: 'Lot Number' },
    { value: 'productionDate', label: 'Production Date' },
    { value: 'standardSellPrice', label: 'List Price' },
    { value: 'status', label: 'Status (Active/Sold)' },
    { value: 'fdaRegulated', label: 'FDA Regulated' },
    { value: 'temperatureMin', label: 'Min Temp (°F)' },
    { value: 'temperatureMax', label: 'Max Temp (°F)' },
    { value: 'warehouse', label: 'Warehouse / DC' },
  ],
  SALES_FILTER_DEFAULTS: {
    BUYERS: [
      'Whole Foods Market Regional',
      'Metro Salvage Provisions',
      'Appalachian Fresh Outlets',
      'Big Lots Food Disposals',
    ],
    DCS: [
      'Northeast Logistics Hub, Newark',
      'Texas Central Facility, Dallas',
      'Pacific Northwest Hub',
    ],
    PRICE_RANGES: [
      '< $10/cs',
      '$10 - $20/cs',
      '> $20/cs',
    ],
    STATUSES: [
      'Completed / Settled',
      'Pending Escrow',
      'Invoiced',
    ],
  },
  SALES_MAPPING_OPTIONS: [
    { value: 'sku', label: 'SKU' },
    { value: 'description', label: 'Description' },
    { value: 'brand', label: 'Brand' },
    { value: 'lotNumber', label: 'Lot Number' },
    { value: 'buyerEmail', label: 'Buyer Email' },
    { value: 'buyerCompany', label: 'Buyer Company' },
    { value: 'quantity', label: 'Quantity Sold (Cases)' },
    { value: 'price', label: 'Price Per Case' },
    { value: 'totalValue', label: 'Total Value' },
    { value: 'revenue', label: 'Total Revenue' },
    { value: 'saleDate', label: 'Sale Date' },
    { value: 'invoiceNumber', label: 'Invoice #' },
    { value: 'productName', label: 'Product Name' },
    { value: 'status', label: 'Status' },
    { value: 'warehouse', label: 'Warehouse / DC' },
  ],
  DEFAULT_SALES_RECORDS: [],
  BUYER_FILTER_DEFAULTS: {
    TIERS: [
      'Tier 1',
      'Tier 2',
      'Custom',
      'Liquidator',
    ],
    STATUSES: [
      'Active Compliant',
      'Full Opt-In',
      'Allergen Filter',
      'Active Buyers',
      'Inactive Buyers',
      'Opt-Out Bidding',
      'Opt-Out Sales',
    ],
  },
  DEFAULT_BUYER_RECORDS: [],
} as const;



